### PR TITLE
Add rutor & thepiratebay for torrent results

### PR DESCRIPTION
**Pull request by amogusussy**
This PR adds rutor and thepiratebay as extra torrent search engines.
I haven't been able to test if this works, since I don't have a VPN and my ISP blocks torrent sites, so please check if it does work.

### CODE REVIEW

**Comment by Extravi** [comment]
```[2023-10-12 00:47:11,894] ERROR in app: Exception on /search [GET]
Traceback (most recent call last):
  File "/home/hecker/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hecker/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hecker/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hecker/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/mnt/c/Users/hecker/Desktop/tailsx-torrenttest/araa-search/__init__.py", line 164, in search
    return torrents.torrentResults(query)
  File "/mnt/c/Users/hecker/Desktop/tailsx-torrenttest/araa-search/src/torrents.py", line 41, in torrentResults
    return render_template("torrents.html",
  File "/home/hecker/.local/lib/python3.10/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/home/hecker/.local/lib/python3.10/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/home/hecker/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/hecker/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/mnt/c/Users/hecker/Desktop/tailsx-torrenttest/araa-search/templates/torrents.html", line 1, in top-level template code
    {% extends "results_layout.html" %}
  File "/mnt/c/Users/hecker/Desktop/tailsx-torrenttest/araa-search/templates/results_layout.html", line 112, in top-level template code
    {% block body %}{% endblock %}
  File "/mnt/c/Users/hecker/Desktop/tailsx-torrenttest/araa-search/templates/torrents.html", line 11, in block 'body'
    <p class="stats">{% if result["views"] is not None %}{{ result["views"] }} views • {% endif %}{{ result["size"] }}</p>
jinja2.exceptions.TemplateRuntimeError: No test named 'None' found.
127.0.0.1 - - [12/Oct/2023 00:47:11] "GET /search?q=google&t=torrent HTTP/1.1" 500 -```

**Comment by amogusussy** [comment]
Did you clone the right branch? I made another branch a few weeks ago named `More_torrent_sites` (note the capital M), which has that issue in it. The line `<p class="stats">{% if result["views"] is not None %}{{ result["views"] }} views • {% endif %}{{ result["size"] }}</p>` isn't in this branch.
This branch doesn't have that issue.

Here's the command to clone it:
```
git clone https://github.com/amogusussy/araa-search/ -b more_torrent_sites
```

**Comment by Extravi** [comment]
also btw about the vpn part proton vpn is a good free vpn idk I personally trust proton mail/vpn because I have been using them for years

**Comment by Extravi** [comment]
i cant pull this for now as the last pr is broken for nyaa

**Comment by Extravi** [comment]
image

**Comment by Extravi** [comment]
read the url

**Comment by Extravi** [comment]
and sometimes it just does numbers with comments 
image

**Comment by Extravi** [comment]
image
none of the nyaa links work at all

**Comment by Extravi** [comment]
nothing else will be added to torrent search into this is fixed

**Comment by Extravi** [comment]
@TEMtheLEM if you want to fix this you can give it a shot because i won't be

**Comment by Extravi** [comment]
i need to fix/work on more important things

**Comment by amogusussy** [comment]
Nyaa search works now (it's one of the few sites that my ISP doesn't block).

**Comment by Extravi** [comment]
have you considered using proton vpn for testing it's free

**Comment by Extravi** [comment]
idk if you trust proton or not but I personally use and trust there services

**Comment by Extravi** [comment]
anyway later today or this week I will take a look at this pull request idk if I can get to it today

**Comment by Extravi** [comment]
@TEMtheLEM can take a look at it maybe then get back to me

**Comment by amogusussy** [comment]
I tried setting it up yesterday, but can't for some reason. 
I was using their docs for OpenVPN because I use Void Linux, and their GUI isn't supported on Void.
I'll retry it with WireGuard now.

**Comment by Extravi** [comment]
oh alright I just use Ubuntu now because I no longer care about distro customization I used to use Gentoo Linux and Arch

**Comment by Extravi** [comment]
I kinda just use whatever just works so I don't need to care/try to get the prefect desktop

**Comment by Extravi** [comment]
I like ubuntus spin on gnome out of the box it functions well and looks good keeps me focused personally

**Comment by Extravi** [comment]
I don't like windows or things that look like it because I get distracted for some reason

**Comment by amogusussy** [comment]
I couldn't get ProtonVPN to work, so I used RiseupVPN instead.
I just tested it, and there doesn't seem to be any issue with it, other than it taking a long time, which is probably just because I'm using a free vpn.

**Comment by amogusussy** [comment]
The reason it's taking so long is because the DNS server I used (quad9) takes a long time to get torrentgalaxy for some reason.
If I disable torrentgalaxy, it takes 0.56 seconds, compared to the 21 seconds it takes with torrentgalaxy.
So the time issue is to do with the DNS, not the VPN, or my code.

**Comment by Extravi** [comment]
i used to use quad9 i just was whatever dns my vpn comes with

**Comment by Extravi** [comment]
let me know once this pr is ready to be tested/pulled

**Comment by amogusussy** [comment]
Its ready now

**Comment by amogusussy** [comment]
@Extravi Have you tested it yet?
I've already tested it for the most part.

**Pull request merged**
