### PR TITLE
Add AI answer feature for quick answers

### PR DESCRIPTION
**Pull request by amogusussy**
This is in response to  #78.
This uses brave search's AI answer feature to get AI answers to queries.
Here's an example: https://imgur.com/AqJEWsH
It highlights the reference(s) when you hover over a piece of the text, and vice versa.
Do note that it isn't instant, because it uses a JS fetch in the browser, after the page has been rendered. It's done this way to stop it from interfering with the speed of the backend rendering of the page.

### CODE REVIEW

**Comment by Extravi** [comment]
so the javascript is sending the request to the /answers end point right?

**Comment by Extravi** [comment]
i think i can use word fuzzing with something like this to improve accuracy

image

**Comment by Extravi** [comment]
> i think i can use word fuzzing with something like this to improve accuracy
> 
> image

this is something i have been working on for independent search suggestions and recommendations in images etc

**Comment by Extravi** [comment]
its also part of my plan to add in my own index

**Comment by Extravi** [comment]
well it will be partially independent

**Comment by amogusussy** [comment]
> so the javascript is sending the request to the /answers end point right?

Yes. It's controlled in the `getAnswers` function.

**Comment by Extravi** [comment]
> > so the javascript is sending the request to the /answers end point right?
> 
> Yes. It's controlled in the `getAnswers` function.

alright good to know i have a few ideas for this

**Comment by amogusussy** [comment]
What do you mean when you're talking about the independent index? Will it be like google?
This isn't really anything to do with search suggestions, or results, it's just an AI that explains a bunch of different websites in a few lines.

**Review by Extravi — APPROVED** [review]

**Comment by Extravi** [comment]
> What do you mean when you're talking about the independent index? Will it be like google? This isn't really anything to do with search suggestions, or results, it's just an AI that explains a bunch of different websites in a few lines.

i can use word fuzzing to improve the accuracy for query to the api endpoint if the api is not using it by default

**Comment by Extravi** [comment]
> > What do you mean when you're talking about the independent index? Will it be like google? This isn't really anything to do with search suggestions, or results, it's just an AI that explains a bunch of different websites in a few lines.
> 
> I can use word fuzzing to improve the accuracy of the query to the API endpoint if the API is not using it by default.

like a spell check etc

**Comment by Extravi** [comment]
> What do you mean when you're talking about the independent index? Will it be like google? This isn't really anything to do with search suggestions, or results, it's just an AI that explains a bunch of different websites in a few lines.

yeah i know but i just wanted to kinda give an update of what i am doing

**Comment by Extravi** [comment]
> > What do you mean when you're talking about the independent index? Will it be like google? This isn't really anything to do with search suggestions, or results, it's just an AI that explains a bunch of different websites in a few lines.
> 
> yeah i know but i just wanted to kinda give an update of what i am doing

Araa will try to be partially independent for news videos etc so it can mix it in with google and others engines when i try to add them

**Comment by Extravi** [comment]
> > > What do you mean when you're talking about the independent index? Will it be like google? This isn't really anything to do with search suggestions, or results, it's just an AI that explains a bunch of different websites in a few lines.
> > 
> > 
> > yeah i know but i just wanted to kinda give an update of what i am doing
> 
> Araa will try to be partially independent for news videos etc so it can mix it in with google and others engines when i try to add them

I will however include a fallback for everything

**Comment by Extravi** [comment]
code look good to me but i will be making some edits soon

**Comment by Extravi** [comment]
nothing crazy tho

**Comment by Extravi** [comment]
odd fails locally with a vpn
image

**Comment by Extravi** [comment]
not sure if it will work on a server

**Comment by amogusussy** [comment]
Okay. 
How will the fuzzing work though? Isnt  fuzzing for comparing two strings? How will it generate a better query from just one string?
It sounds like it could be useful though. Brave's API usually only responds if you start a search with 'what is', or something like that.

**Comment by Extravi** [comment]
> Okay. How will the fuzzing work though? Isnt fuzzing for comparing two strings? How will it generate a better query from just one string? It sounds like it could be useful though. Brave's API usually only responds if you start a search with 'what is', or something like that.

I would have to look into it. I could just make a JSON file or data set to go off of.

**Comment by Extravi** [comment]
> > Okay. How will the fuzzing work though? Isnt fuzzing for comparing two strings? How will it generate a better query from just one string? It sounds like it could be useful though. Brave's API usually only responds if you start a search with 'what is', or something like that.
> 
> I would have to look into it. I could just make a JSON file/dataset to go off of.

this will be the same thing i will be using for Wikipedia searches in the local index

**Comment by Extravi** [comment]
> > > Okay. How will the fuzzing work though? Isnt fuzzing for comparing two strings? How will it generate a better query from just one string? It sounds like it could be useful though. Brave's API usually only responds if you start a search with 'what is', or something like that.
> > 
> > 
> > I would have to look into it. I could just make a JSON file/dataset to go off of.
> 
> this will be the same thing i will be using for Wikipedia searches in the local index

it would scrape and lookup based on this and other factors 
image

**Comment by Extravi** [comment]
> > > > Okay. How will the fuzzing work though? Isnt fuzzing for comparing two strings? How will it generate a better query from just one string? It sounds like it could be useful though. Brave's API usually only responds if you start a search with 'what is', or something like that.
> > > 
> > > 
> > > I would have to look into it. I could just make a JSON file/dataset to go off of.
> > 
> > 
> > this will be the same thing i will be using for Wikipedia searches in the local index
> 
> it would scrape and lookup based on this and other factors image

so unlike librex and others i can pickup on templeos so the user wont need to put in something like TempleOS

**Comment by Extravi** [comment]
idk i am still working on everything and school so it will take time for me to add theses things

**Comment by Extravi** [comment]
had to revert for now sorry

**Comment by amogusussy** [comment]
Why did you revert it?

**Comment by Extravi** [comment]
something wasn't working correctly I need to look into it later but not this week I need to work on other stuff

**Comment by amogusussy** [comment]
Idk, it seems to work on and off for some reason. 
I can do a request to `http://localhost:8000/answers?q=who%20founded%20google` one moment, refresh the next, and it returns that its failed.
I think it's probably something to do with rate limiting from brave.

**Comment by amogusussy** [comment]
I'll look into it.

**Pull request merged**
