### PR TITLE
I added three new themes

### PR DESCRIPTION
**Pull request by SillyBilly10**
There's probably going to be an issue or fourteen, but they look neat nevertheless.

### CODE REVIEW

**Comment by amogusussy** [comment]
You'll need to add a way for users to enable the themes.
You can add this in the `templates/settings.html` file after line 17:
```
<option value="catppuccin_mocha_blue" {% if theme == 'catppuccin_mocha_blue' %}selected{% endif %}>Catppuccin Mocha Blue</option>
<option value="gentoo_lavender" {% if theme == 'gentoo_lavender' %}selected{% endif %}>Gentoo Lavender</option>
<option value="red" {% if theme == 'red' %}selected{% endif %}>Red</option>
```

Also, the Catppuccin Mocha Blue theme and the Red theme are the same file. If you used the upload feature on Github, double check that you chose the right files.

**Comment by Extravi** [comment]
image
image
image

**Comment by Extravi** [comment]
man idk how i feel about this

**Comment by Extravi** [comment]
i think i will just add a custom css settings

**Comment by Extravi** [comment]
so i wont need to add it into the main repos

**Comment by Extravi** [comment]
so i wont need to add it into the main repos

**Comment by Extravi** [comment]
[gentoo_lavender.css](https://github.com/Extravi/tailsx/pull/53/files#diff-296375607ece76327ef20baaa90ed27af6b2c1c2a16afe5e96917fc8f137c667) does look alright tho

**Comment by Extravi** [comment]
so that might get added

**Comment by SillyBilly10** [comment]
Yeah that red theme had too bright of a background, I tried fixing it a little, I also tried making diff colors but I'm really not an expert on css lmao, BTDubs, you should maybe consider having the safesearch button things switched to the color that the next button is using. Tell me what you think about this[cid:3a28a12e-2a6e-40b1-b50c-cf9876840597][cid:d0dee3c0-d909-441b-9e9f-1f8e39f5762d][cid:21517d08-0b51-4310-9c75-eb1d89acd78e]
________________________________

**Comment by SillyBilly10** [comment]
i updated two time, pls respo

**Comment by Extravi** [comment]
looking into it i just have to finish school work first i am in college

**Comment by Extravi** [comment]
also style.css is not to be edited for themes

**Comment by Extravi** [comment]
image

**Comment by Extravi** [comment]
do not edit style.css it will break stuff and other themes etc

**Comment by SillyBilly10** [comment]
All I remember doing was changing the color of three buttons so that they would better fit all the styles

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SillyBilly10** [comment]
Ok fine I did it, I unedited styles.css, but I liked the styled buttons more

**Comment by SillyBilly10** [comment]
i updated it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SillyBilly10** [comment]
i updated it a while ago, no conflicts it shows

**Comment by Extravi** [comment]
i want to make a shop for user themes first

**Comment by Extravi** [comment]
i am redoing settings

**Comment by Extravi** [comment]
however themes in settings will now need javascript

**Comment by Extravi** [comment]
Screenshot from 2023-10-06 23-20-08

**Comment by Extravi** [comment]
i am rewriting settings etc there will be quick menus and a full settings pages with user themes and previews

**Comment by amogusussy** [comment]
@Extravi, how will this work for non-javascript users? Will there be a fallback page for if you've not got JS enabled?

**Comment by Extravi** [comment]
it will just disabled it

**Comment by Extravi** [comment]
non javascript users aren't my priority

**Comment by amogusussy** [comment]
>it will just disabled it
Disable settings, or just disable this popup?

**Comment by Extravi** [comment]
just the pop up and settings just wont be as complete for non javascript users

**Comment by Extravi** [comment]
however settings will still exist just a different version of it

**Comment by Extravi** [comment]
i will add your themes soon 
image
i am still working on the new settings menu and fixing up mistakes from yesterday

**Comment by Extravi** [comment]
now i will officially only support 3 themes but there will be a place in settings for user maintained themes

**Comment by Extravi** [comment]
image

**Comment by Extravi** [comment]
user themes will have its own dir at /discover
image

**Comment by Extravi** [comment]
https://github.com/Extravi/araa-search/assets/98912029/c6b69462-3f11-4cca-b61b-20ffe4005554


i am adding your themes today with this update

**Comment by Extravi** [comment]
@SillyBilly10

**Comment by Extravi** [comment]
image
this one looks cool in the settings menu

**Comment by Extravi** [comment]
nice

**Comment by SillyBilly10** [comment]
Ill try the new update soon, thanks for the updates!

**Comment by Extravi** [comment]
i already added it into the code base i just need to update my instances https://github.com/Extravi/araa-search/commit/467d746d6965cafaec8e72d448ac68a5dda8daa7

**Comment by Extravi** [comment]
thanks

**Pull request closed without merging**
