### PR TITLE
Change image viewer design

### PR DESCRIPTION
**Pull request by amogusussy**
Here's what the new design looks like:
Screenshot

These changes make the image viewer look a lot cleaner.

In the current viewer, it says 'View full resolution image with proxy', when the link isn't actually a proxy.
This also uses icons, rather than text, because icons are more user friendly, and more intuitive.

### CODE REVIEW

**Comment by Extravi** [comment]
i might try my own thing first when i have time like my own design/take on this

**Comment by Extravi** [comment]
i'm very picky with web design and have my own style i like to use

**Comment by amogusussy** [comment]
Do you have any ideas for a newer design?

**Comment by Extravi** [comment]
right now I'm just trying to make the project more reliable https://github.com/Extravi/araa-search/issues/103

**Comment by Extravi** [comment]
not planned atm

**Pull request closed without merging**
