### PR TITLE
Improve image page design

### PR DESCRIPTION
**Pull request by amogusussy**
This is a duplicate of #96 because I forgot to change my global git email.

Here's the original text:
This PR does a few things to improve the image page.
It simplifies the images.py and images.html code, so that it's a lot more easier to read.
It adds a title and domain to all of the images.
It adds a box around the selected image.
And it adds a box in the bottom left showing the resolution of the original image.
It also shows the a link to the full size image in when you open the image menu.

These changes are mainly based on qwant's image page, since I think that looks quite good.

### CODE REVIEW

**Comment by Extravi** [comment]
can i get a screenshot please

**Comment by Extravi** [comment]
why remove .images from the theme style sheet its there because of both light themes and dark themes and light themes have its own style for it

**Comment by Extravi** [comment]
image

**Comment by Extravi** [comment]
image

**Comment by Extravi** [comment]
does this break any of the current themes?

**Comment by Extravi** [comment]
and did you move .images

**Comment by amogusussy** [comment]
I'm on my phone now, but will get a screenshot later.

That style being removed is because it adds a shadow around the .jmage class. With the changes ive made, the .image class includes the title, and domain name, so if i leave this, its adds a shadow around the entire element, not just the image.

I've put a style in styles.css to just add the shadow around the image, rather than the entire class.

**Comment by amogusussy** [comment]
Here's the screenshot

I forgot to mention, but this also removes the `View full resolution image with ` link. This is because the link doesn't actually show the full image. It only shows the small thumbnail image.

**Comment by Extravi** [comment]
did you change the themes border color?

**Comment by Extravi** [comment]
idk I'm on mobile so I'm not sure I'll download and test the repo later

**Comment by Extravi** [comment]
but the website and title preview is cool something I wanted to do for some time now

**Comment by Extravi** [comment]
I don't really like these back-end changes tho or wording changes

**Comment by amogusussy** [comment]
>did you change the themes border color?

Do you mean the shadow on the image? If so, yes. I've set them all to black (line 282).

Now that I re-read it, the `View full resolution image: full` doesn't make sense. What do you suggest I change it to?
Having an extra line for the full image size is still good imo. For example, if you wanted to find a wallpaper, you'll probably want to know that the image isn't a really low quality. I think the `Image proxy size` could change though, since that makes it seem like the proxy is making it smaller, when that's just the original size of the thumbnail.

Is there anything in particular that you don't like about the backend? I prefer it, since it removes the array indexing in the template files. Without going back to images.py, you'll never remember what `result[0]` is, whereas with `result.title`, it's a lot more clearer what it's doing.

**Comment by Extravi** [comment]
yeah "View full resolution image: full" doesn't make sense i would just set it to what i already had 

View full resolution image with proxy

**Comment by amogusussy** [comment]
Saying to view it with a proxy would also not make sense, since this isn't the proxy, it's the original image source.

I think I might redesign the image viewer so that it's more inline with qwant's viewer, where there's icons rather than words.

**Comment by amogusussy** [comment]
Like this:

Screenshot_2023-12-22_20-23-27

**Comment by Extravi** [comment]
I don't really like that I can make the changes myself that I like

**Comment by Extravi** [comment]
I'll look into it later

**Comment by amogusussy** [comment]
I didn't see your reply, so I started working on it anyway.
I'll upload a comparison before I commit the changes.
New image viewer:
new-image
Old viewer:
old-image

**Comment by amogusussy** [comment]
I think I'll add a line at the bottom for an attribution to qwant's engine to fill some of the empty space.

**Comment by Extravi** [comment]
I would much rather keep design to me

**Comment by Extravi** [comment]
I'll be better if you put the new image viewer design in a different pull request

**Comment by Extravi** [comment]
I'm probably going to make changes to this pull request later

**Comment by Extravi** [comment]
but please do not edit the image viewer itself in this pull request

**Comment by amogusussy** [comment]
The changes depend on this pull request, so I can't open a separate one.
I haven't committed the changes yet, so if you pull the PR, I can then make another PR for these changes, then make a separate discussion on the changes.

**Comment by Extravi** [comment]
image
image


why wont this fit the same anymore?

**Comment by Extravi** [comment]
nvm i noticed it's getting slightly lower resolution images did you make that change?

**Comment by Extravi** [comment]
fixed the border breaking the images 
image

**Comment by Extravi** [comment]
image
image

**Comment by Extravi** [comment]
image

**Comment by Extravi** [comment]
ill fix it later if i want

**Comment by Extravi** [comment]
first ill see if speeds are better without it

**Review by Extravi — APPROVED** [review]

**Comment by Extravi** [comment]
thanks

**Comment by Extravi** [comment]
since i edited the html in this pr the js has this bug because i removed an html element 
image

**Comment by Extravi** [comment]
also i upgraded the official instance its fast for me even tho im in canada but it should be very fast for you because its closer

**Pull request merged**
