### PR TITLE
Change wiki snippet ui

### PR DESCRIPTION
**Pull request by amogusussy**
image

### CODE REVIEW

**Comment by Extravi** [comment]
the wiki thing seems to have an issue because this works
https://tailsx.com/search?q=among+us&t=text
but not this
https://araa.extravi.dev/search?q=among+us&t=text
image

**Comment by Extravi** [comment]
also i dont think it should return none when something is not there 
image
image

**Comment by amogusussy** [comment]
Both those cases now work with the last two commits

**Review by Extravi — APPROVED** [review]

**Comment by Extravi** [comment]
thank you

**Pull request merged**
