### PR TITLE
Add view source button to torrents

### PR DESCRIPTION
**Pull request by amogusussy**
This PR adds a link under each torrent that links to the original post for the torrent. This is useful for if you're downloading software and want to check if the person who made the torrent is well known and trusted.

A lot of the PR is also just changing a few things so that they conform with the PEP 8 style guide, so that my editor stops giving me tons of errors.

### CODE REVIEW

**Comment by amogusussy** [comment]
I've also just made some changes to add multiprocessing, which makes the torrent requests go a lot faster (~4 times faster).
I'll make a separate PR for that once this has been merged.

**Comment by Extravi** [comment]
> I've also just made some changes to add multiprocessing, which makes the torrent requests go a lot faster (~4 times faster). I'll make a separate PR for that once this has been merged.

you can add it into this pr if you want ill wait

**Comment by amogusussy** [comment]
Ok. Ill do it when i get home later.

**Comment by Extravi** [comment]
let me know once this pr is ready thanks

**Comment by amogusussy** [comment]
I think it should be ready now. Can you just check if it's working for torrentgalaxy? I get a ConnectionTimeoutError for torrentgalaxy (it's blocked).
I've rewritten torrentgalaxy's search function because it was too complicated to add the view source link to it in the way that it was (this also makes adding things in the future easier), so there's probably gonna be some issues with that, because I've no way of checking if it works or not.

**Review by Extravi — APPROVED** [review]
code looks good ill test it later before pulling it

**Comment by amogusussy** [comment]
Its probably because i said `results` instead of `result`.

**Comment by amogusussy** [comment]
Can you test it now?

**Comment by amogusussy** [comment]
Can it be merged yet?

**Comment by Extravi** [comment]
oh I forgot about this I'll test later

**Comment by Extravi** [comment]
```python3
Process Process-7:
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hecker/Downloads/araa-search-torrent_api_values/src/torrent_sites/torrentgalaxy.py", line 52, in search
    "magnet": helpers.apply_trackers(list_of_anchors[4]),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hecker/Downloads/araa-search-torrent_api_values/src/helpers.py", line 232, in apply_trackers
    name = get_magnet_name(hash)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hecker/Downloads/araa-search-torrent_api_values/src/helpers.py", line 227, in get_magnet_name
    return magnet.split("&dn=")[1].split("&tr")[0]
           ^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
```

**Comment by amogusussy** [comment]
Could you show the output when you print the `list_of_anchors` variable?

**Comment by amogusussy** [comment]
I think the commit I just did should fix this issue.

**Comment by Extravi** [comment]
That does not return any errors, but it also won't return any results from torrentgalaxy. I tested it both on my ISP's network and a VPN.

**Comment by Extravi** [comment]
You could try this for testing and download the config file from the settings on their website; they do have free servers.

https://protonvpn.com/support/wireguard-manual-linux/

**Comment by amogusussy** [comment]
Can you check if it's even returning anything in the python request? Try printing the `soup` variable after it's declared. It might be because the request isn't finishing in the 8 second time period set for the timeout.

**Comment by amogusussy** [comment]
I've just installed the VPN, and tested it. [It ends up getting rate limited though](https://i.imgur.com/nu8Kq1P.png). 
Even if I use the normal araa.extravi.dev instance, there's no torrentgalaxy results. So it's probably been rate limited too.
I think we should probably just remove TG now. Maybe replace it with something else, like YTS.

**Comment by Extravi** [comment]
> I've just installed the VPN, and tested it. [It ends up getting rate limited though](https://i.imgur.com/nu8Kq1P.png). Even if I use the normal araa.extravi.dev instance, there's no torrentgalaxy results. So it's probably been rate limited too. I think we should probably just remove TG now. Maybe replace it with something else, like YTS.

yeah i just checked my instance is getting rate limited but i still think we should keep torrentgalaxy because the results are very good

**Review by Extravi — APPROVED** [review]

**Comment by Extravi** [comment]
thank you ill pull this now

**Comment by Extravi** [comment]
https://araa.extravi.dev/search?q=test&t=torrent

does not work on my server for some reason ill check 
Screenshot_20240217_001946

**Comment by Extravi** [comment]
it randomly started working so i cant even test and find out why

**Comment by Extravi** [comment]
it works only when i already have an ssh session but when i close the ssh session it breaks

**Comment by Extravi** [comment]
so i need to keep an open ssh session for it to work idk why

**Comment by Extravi** [comment]
also why was urlparse removed?

**Comment by amogusussy** [comment]
You could try setting debug=True in app.run in the __init__.py file. Then see what errors show up.
Did you remove torrentgalaxy? It's probably because of some issue with that.
I'll make a PR to remove torrentgalaxy in a few minutes.

`urlparse` was removed because it wasn't used anywhere in the file, so importing it had no purpose.

**Comment by amogusussy** [comment]
You could try setting debug=True in app.run in the __init__.py file. Then see what errors show up.
Did you remove torrentgalaxy? It's probably because of some issue with that.
I'll make a PR to remove torrentgalaxy in a few minutes.

`urlparse` was removed because it wasn't used anywhere in the file, so importing it had no purpose.

**Comment by Extravi** [comment]
https://github.com/Extravi/araa-search/commit/fecc69065f9be3ca27893f942b948df9b5007d07

i removed this pr this does not fix the issue on my server https://github.com/Extravi/araa-search/pull/124

the issue is not torrentgalaxy its something in this pr because it only works when i have an active ssh session to the server

**Comment by Extravi** [comment]
Screenshot_20240218_182902

**Comment by Extravi** [comment]
and torrentgalaxy works fine on my instance with an older version of the code

**Comment by Extravi** [comment]
Screenshot_20240218_183014
also speed is not much of an issue with the older version so maybe we should just keep using it

**Comment by Extravi** [comment]
we can however add back the view source button as that works without issue

**Pull request merged**
