### PR TITLE
adjusted bang redirects

### PR DESCRIPTION
**Pull request by unstablemaple**
See [#69](https://github.com/Extravi/araa-search/issues/69#issuecomment-1756347345)

### CODE REVIEW

**Comment by amogusussy** [comment]
This wont work, because if someone where to enter `!gh` for github, it would also pick up `!g` for google, so instead of being sent to github, you're sent to google.
You could try splitting it by spaces, then checking if the bang is in the array. Like this:
```
if BANG in query.lower().split(" "):
    do_something()
```

**Comment by unstablemaple** [comment]
@amogusussy I don't understand how my modification would pickup `!g` in a query with `!gh` I just tested it on my instance, it redirects to GitHub. Here's the chunk of the code again:

```  python   
   if BANG in query:
            query += " " # Simple fix to avoid a possible error 500
                         # when parsing the query for the bangkey.
            bang_index = query.index(BANG)
            bangkey = query[bang_index+1:query.index(" ", bang_index)].lower()
            if SEARCH_BANGS.get(bangkey) is not None:
                query = query.lower().replace(BANG + bangkey, "").lstrip()
                return app.redirect(SEARCH_BANGS[bangkey].format(query))
            # Remove the space at the end of the query.
            # The space was added to fix a possible error 500 when
            # parsing the query for the bangkey.
            query = query[:len(query) - 1]  
```
The function checks whether the query has a bang `!` then gets the index of the first bang, after that it looks for the `bangkey` and which will basically be in the form of `!<bangkey>` . The `bangkey` will take anything after the `!` and will stop when it encounters a `" "` , so something like `sample query !ghcode`   will return a bang key of `ghcode`. Same goes for `sample !ghcode query`.

**Comment by unstablemaple** [comment]
The only thing that is different in this implementation from DDG's bangs parsing is that a DDG query like `sample search !g!yt` actually redirects to YouTube and keeps the `!g` in the YouTube search query. While that's easy to implement, I don't that's useful in any sort of way. None of the other meta-engines like LibreX parsed it that way.

**Comment by amogusussy** [comment]
I thought the `if BANG in query` was checking for a specific bang string (like `!g`), not just for the single character `!`.
Sorry for the misunderstanding.

**Comment by Extravi** [comment]
i will look into this soon

**Comment by Extravi** [comment]
does this still work with ! and the other thing you want?

**Comment by Extravi** [comment]
thanks tested and works

**Pull request merged**
