### PR TITLE
Add post method

### PR DESCRIPTION
**Pull request by amogusussy**
This PR adds an option in the settings to use the POST method.

The only issue I've found with this is that the settings at the top of the Web results page doesn't redirect you back to the results you were previously on. If no one can come up with a better solution, I'll just make an if statement to only show it for GET users. This isn't a massive problem, since the settings at the top can still be changed within the settings page.

### CODE REVIEW

**Review by Extravi — APPROVED** [review]

**Comment by Extravi** [comment]
for some reason post breaks image search

**Comment by Extravi** [comment]
who is narutofr?

**Comment by amogusussy** [comment]
I dont know. I just reinstalled my OS, and redid my ssh-keygen stuff for making commits and pushes to github. My guess is that there was some mix up on github's servers with the keys. Granted, i know little to nothing about ssh, so whatever im sayjng is probably wrong. Its still quite weird though.

**Comment by Extravi** [comment]
somewhat old account too idk

**Comment by Extravi** [comment]
oh okay

**Comment by TEMtheLEM** [comment]
That's pretty funny, lmao

**Pull request merged**
