### PR TITLE
Patch #59

### PR DESCRIPTION
**Pull request by TEMtheLEM**
Patches issues with #59 and gets it working.

Subsequently, the docker image also now allows users to configure `NYAA_DOMAIN` and what sites are enabled (`ENABLED_TORRENT_SITES`). This change is only present due to the patch.

### CODE REVIEW

**Comment by amogusussy** [comment]
What changes (beside the docker stuff) are made from my original code?

**Comment by Extravi** [comment]
?

**Comment by TEMtheLEM** [comment]
@amogusussy

- `src/torrent_sites/nyaa.py` is no different.
- `src/torrent_sites/torrentgalaxy.py` has the following changes;
```diff
-    view_counts = [int(div.find("font", {"color": "orange"}).text) for div in result_divs]
-    seeders = [int(div.find("font", {"color": "green"}).text) for div in result_divs]
-    leechers = [int(div.find("font", {"color": "#ff0000"}).text) for div in result_divs]
+    view_counts = [int(div.find("font", {"color": "orange"}).text.replace(',', '')) for div in result_divs]
+    seeders = [int(div.find("font", {"color": "green"}).text.replace(',', '')) for div in result_divs]
+    leechers = [int(div.find("font", {"color": "#ff0000"}).text.replace(',', '')) for div in result_divs]
```
`text.replace(',','')` is used as the text could include commas, and Python cannot parse integers from those strings.
- `src/torrents.py` has no effective difference, other than the quoting you added on 9/25. Just realized time is imported twice, however, but this shouldn't (and didn't seem to) affect anything. I'll clean that up soon.
- `templates/torrents.html` has the following changes;
```diff
-            <a id="link" href="{{ result["magnet"] }}">{{ result["href"] }}</a>
+            <a id="link" href="{{ result['magnet'] }}">{{ result["href"] }}</a>
```
^ The double quotes in double quotes seemed wrong. Can't remember if this caused any actual bugs or not, but regardless my text editor took `"{{ result["magnet"] }}"` weirdly, so I changed it to `"{{ result['magnet'] }}"`.
```diff
-            <a class="torrent" href="{{ result["magnet"] }}"><h3>{{ result["title"] }}</h3></a>
+            <a class="torrent" href="{{ result['magnet'] }}"><h3>{{ result["title"] }}</h3></a>
```
^ Same story here.
```diff
-            <p class="stats">{% if result["views"] is not None %}{{ result["views"] }} views • {% endif %}{{ result["size"] }}</p>
+            <p class="stats">{% if result["views"] %}{{ result["views"] }} views • {% endif %}{{ result["size"] }}</p>
```
^ Flask got mad about `{% if result["views"] is not None %}` and crashed there. It didn't like `is not None`, so I removed that and relied on truthiness instead. That solution ended up working.

And I think that's all for the differences. Again, a lot of it is your old code, but with all the applicable patches that I went over.

**Comment by TEMtheLEM** [comment]
@Extravi anything you specifically need me to clear up? I'm not sure what you're confused about. This PR patches all the issues (that at least I encountered) with PR #59.

**Comment by TEMtheLEM** [comment]
Also, just to parody recent changes you made, I've just quoted the queries in both `src/torrent_sites/nyaa.py` and `src/torrent_sites/torrentgalaxy.py`. See the most recent commit.

**Comment by amogusussy** [comment]
Okay, thank you :)

**Comment by Extravi** [comment]
this has some of amogusussys code so @amogusussy you fine if i pr this?

**Comment by amogusussy** [comment]
Yes :+1:

**Comment by TEMtheLEM** [comment]
Resolved merge conflicts.

@Extravi PLEASE merge this before doing ANYTHING else.

**Review by Extravi — APPROVED** [review]

**Pull request merged**
