### PR TITLE
Add wikipedia information for the snippet at the right

### PR DESCRIPTION
**Pull request by amogusussy**
This pr adds all the various facts that google adds underneath the wikipedia section.

Here's an example:
image

The UI isn't that good right now, so please suggest some changes.

### CODE REVIEW

**Comment by Extravi** [comment]
that looks really good I can't take a look at it right now but I will soon also how does it look on mobile?

**Comment by amogusussy** [comment]
image

**Review by Extravi — APPROVED** [review]

**Comment by Extravi** [comment]
thank you

**Comment by Extravi** [comment]
image
do you think this looks better without the hr tag? 
```css
.wiki_known_for {
  margin: 0px;
  font-weight: normal;
  margin-bottom: 8px;
}
```

**Comment by Extravi** [comment]
duckduckgo does the same thing 
image

**Comment by amogusussy** [comment]
Yeah, it does look better. I was just trying to replicate google's wiki box.

I think the aligned results on ddg's look nice too.

**Pull request merged**
