### PR TITLE
Add sublinks to qwant and show current engine

### PR DESCRIPTION
**Pull request by amogusussy**

### CODE REVIEW

**Review by Extravi — APPROVED** [review]

**Comment by Extravi** [comment]
thank you

**Comment by amogusussy** [comment]
@Extravi Why hasn't the main instance been updated?

**Comment by Extravi** [comment]
ill do that today

**Comment by Extravi** [comment]
image
i dont like how it shows the engine it looks off to me its better if thats hidden

**Comment by amogusussy** [comment]
Okay. It could look a bit better if it was under the wiki snippet box.

**Comment by Extravi** [comment]
i really dont want to show it it should be hidden and only shown in the api

**Pull request merged**
