### PR TITLE
Minor tweaks to videos

### PR DESCRIPTION
**Pull request by unstablemaple**
- Thumbnails are now clickable
- Fixed the issue when using a different Invidious instance 

You can test the changes on my instance.

### CODE REVIEW

**Comment by Extravi** [comment]
i cant edit the pull request but i wanted to set the default instance back yt.artemislena.eu before pulling

**Comment by Extravi** [comment]
image

**Comment by unstablemaple** [comment]
@Extravi edited.

**Comment by Extravi** [comment]
thank you

**Pull request merged**
