### PR TITLE
Switch instances

### PR DESCRIPTION
**Pull request by amogusussy**
This adds a menu for the user to switch instances through a new instances.json file.
This shows up when there's no search results, and under the settings button in the nav bar.
You'll need to change the `INSTANCE_SOURCE` variable in `_config.py` before merging, otherwise it will get the instances from my repo.
If there's anything you want changing, or any bugs, just let me know.

### CODE REVIEW

**Comment by Extravi** [comment]
have not tested it yet but i am not sure about it atm because i was about to start working on something else to better avoid the "are you a robot" thing

**Comment by Extravi** [comment]
idk i need more time to look into everything

**Comment by amogusussy** [comment]
okay :+1:

**Comment by amogusussy** [comment]
@Extravi
Will this ever be merged, or not?

**Comment by Extravi** [comment]
idk leave it for now maybe some day

**Comment by Extravi** [comment]
depending on what i do

**Comment by Extravi** [comment]
i want to add a shop like thing to tailsx like custom js and themes users can add without it going into the code

**Comment by Extravi** [comment]
kinda like a discord mod

**Comment by Extravi** [comment]
it should make tailsx the most customizable open source meta search engine out there on the users end

**Comment by Extravi** [comment]
so i will be removing settings and it will be replaced with something much better and new

**Comment by Extravi** [comment]
something like this might get built in

**Comment by Extravi** [comment]
there are many things i want to add and know how to add i just dont have the time to do it atm with school and everything

**Comment by Extravi** [comment]
https://github.com/Extravi/tailsx/pull/53

will be the first themes in the shop and later i will add javascript support

**Comment by amogusussy** [comment]
Is there any reason why this cant be added now, and then later add the theme store? It doesn't seem like there'd be any overlap between the two.

**Comment by amogusussy** [comment]
Id happily redo the pr if theres any issues.

**Comment by amogusussy** [comment]
I think I'll redo this PR sometime in the future.

**Pull request closed without merging**
