### PR TITLE
remove torrentgalaxy

### PR DESCRIPTION
**Pull request by amogusussy**

### CODE REVIEW

**Comment by Extravi** [comment]
but it worked only when I had an open ssh session to the server torrent search only doesn't work when I close the ssh session

**Comment by amogusussy** [comment]
Were there any tgx results with the ssh session open? It's probably that `soup.findAll("div", {"class": "tgxtablerow"})` returned nothing, because its rate limited so there's no results, and then the for loop didn't execute. When you logged off the ssh session, the rate limit probably expired, then there was some error in my code, which causes it to fail.
I think it should still be removed. Araa should strive toward being stable, and using a service that works one minute, then doesn't the next, is the opposite of stability.

**Comment by Extravi** [comment]
no like I tested it more than once if I ssh back into my server it works and if I ssh out it just starts to fall

**Comment by Extravi** [comment]
I'll test it again later

**Comment by Extravi** [comment]
if that's the case why not try to get the results when possible and if it returns nothing handle the error and exclude the results for that site

**Comment by Extravi** [comment]
> Were there any tgx results with the ssh session open? It's probably that `soup.findAll("div", {"class": "tgxtablerow"})` returned nothing, because its rate limited so there's no results, and then the for loop didn't execute. When you logged off the ssh session, the rate limit probably expired, then there was some error in my code, which causes it to fail.
> I think it should still be removed. Araa should strive toward being stable, and using a service that works one minute, then doesn't the next, is the opposite of stability.

trust me I want it to be stable and I care about that but why remove things it already has why not fix the issues it's having so it would just be excluded if it has an error

**Comment by amogusussy** [comment]
I've found a way around the captcha.

Make a separate session for torrentgalaxy.
Check if the captcha's there.
Download the audio file (from the href on the speaker icon). Use the same session to keep the `PHPSESSID` cookie, so the audio and the image match up.
Write it to a file.
Use [assemblyai](https://www.assemblyai.com/) to get the text from the audio. Replace words like 'three' with 3, then remove all space.
Submit with that text.
Then it should work for one hour. After then, repeat the process.

I just don't know how to add this in the project. It takes ~10 seconds to do the full process, so having it execute while the torrents are loading isn't reasonable.

**Comment by amogusussy** [comment]
We could also use a captcha solver like what there is with google.

**Comment by Extravi** [comment]
> We could also use a captcha solver like what there is with google.

does not work well because sometimes google chrome breaks and wont restart without a system restart

**Comment by Extravi** [comment]
so the solver gets stuck being set to "true"

**Comment by Extravi** [comment]
i ssh into my server it starts to work again

**Comment by Extravi** [comment]
i ssh out than its all broken

**Comment by Extravi** [comment]
ill pull this test without ssh and revert if this does not fix it

**Comment by Extravi** [comment]
no this pull request does not fix it

**Pull request merged**
